{{- if .Values.loki.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "resource.default.name" . }}-loki-read-api
  namespace: {{ .Values.loki.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- with .Values.loki.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.loki.hostname }}
  hostnames:
  - {{ tpl . $ | quote }}
  {{- end }}
  rules:
  - backendRefs:
    - name: loki-gateway
      namespace: {{ .Values.loki.namespace }}
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /loki/api/v1/labels
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/label
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/rules
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/query
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/index
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/query_range
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/series
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    - path:
        type: PathPrefix
        value: /loki/api/v1/detected_labels
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: X-Scope-OrgID
          value: "%REQ(X-Scope-OrgID)%"
  - backendRefs:
    - name: loki-gateway
      namespace: {{ .Values.loki.namespace }}
      port: 80
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: {{ include "resource.default.name" . }}-loki-read-api-headers-check
    matches:
    - path:
        type: PathPrefix
        value: /loki/api/v1/labels
    - path:
        type: PathPrefix
        value: /loki/api/v1/label
    - path:
        type: PathPrefix
        value: /loki/api/v1/rules
    - path:
        type: PathPrefix
        value: /loki/api/v1/query
    - path:
        type: PathPrefix
        value: /loki/api/v1/index
    - path:
        type: PathPrefix
        value: /loki/api/v1/query_range
    - path:
        type: PathPrefix
        value: /loki/api/v1/series
    - path:
        type: PathPrefix
        value: /loki/api/v1/detected_labels
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "resource.default.name" . }}-loki-read-api
  namespace: {{ .Values.loki.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "resource.default.name" . }}-loki-read-api
  extAuth:
    http:
      backendRefs:
      - name: dex
        namespace: giantswarm
        port: 5556
      path: /userinfo
      headersToExtAuth:
      - Authorization
      - Cookie
      - X-Scope-OrgID
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: {{ include "resource.default.name" . }}-loki-read-api-headers-check
  namespace: {{ .Values.loki.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  directResponse:
    contentType: text/plain
    statusCode: 400
    body:
      type: Inline
      inline: "Bad Request"
{{- end }}
