{{- if and .Values.mimir.enabled .Values.mimir.routes.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "resource.default.name" . }}-mimir-write-api
  namespace: {{ .Values.mimir.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- with .Values.mimir.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mimir.hostname }}
  hostnames:
  - {{ tpl . $ | quote }}
  {{- end }}
  rules:
  - backendRefs:
    - name: mimir-gateway
      namespace: {{ .Values.mimir.namespace }}
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /prometheus/api/v1/push
      headers:
      - name: X-Scope-OrgID
        value: "^.+$"
        type: RegularExpression
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: {{ include "resource.default.name" . }}-mimir-write-api-rewrite
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: X-Scope-OrgID
          value: "%REQ(X-Scope-OrgID)%"
  - backendRefs:
    - name: mimir-gateway
      namespace: {{ .Values.mimir.namespace }}
      port: 80
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: {{ include "resource.default.name" . }}-mimir-write-api-rewrite
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: {{ include "resource.default.name" . }}-mimir-write-api-headers-check
    matches:
    - path:
        type: PathPrefix
        value: /prometheus/api/v1/push
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "resource.default.name" . }}-mimir-write-api
  namespace: {{ .Values.mimir.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "resource.default.name" . }}-mimir-write-api
  extAuth:
    http:
      backendRefs:
      - name: oauth2-proxy-observability-platform-api
        namespace: monitoring
        port: 4180
      path: /oauth2/observability-platform-api/auth
      headersToExtAuth:
      - Authorization
      - Cookie
      - X-Scope-OrgID
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: {{ include "resource.default.name" . }}-mimir-write-api-rewrite
  namespace: {{ .Values.mimir.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  urlRewrite:
    path:
      type: ReplaceRegexMatch
      replaceRegexMatch:
        pattern: "^/prometheus(/.*)$"
        substitution: "\\1"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: {{ include "resource.default.name" . }}-mimir-write-api-headers-check
  namespace: {{ .Values.mimir.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  directResponse:
    contentType: text/plain
    statusCode: 400
    body:
      type: Inline
      inline: "Bad Request"
{{- end }}
