auth:
  jwt:
    providers:
    - name: azure-ad
      issuer: "https://login.microsoftonline.com/my-tenant/v2.0"
      remoteJWKS:
        uri: "https://login.microsoftonline.com/my-tenant/discovery/v2.0/keys"

loki:
  enabled: true
  hostname: "observability.test.example.com"
  namespace: loki
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system
  basicAuth:
    secretName: "loki-basic-auth"
  read:
    paths:
    - /loki/api/v1/labels
    - /loki/api/v1/query
  write:
    paths:
    - /loki/api/v1/push
    - /otlp/v1/logs
    stripPrefixPaths: []
    grpc:
      backendService: loki-distributor
      backendPort: 9095

mimir:
  enabled: true
  hostname: "observability.test.example.com"
  namespace: mimir
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system
  basicAuth:
    secretName: "mimir-basic-auth"
  read:
    paths:
    - /prometheus/api/v1/labels
    - /prometheus/api/v1/query
  write:
    paths:
    - /otlp/v1/metrics
    stripPrefixPaths:
    - /prometheus/api/v1/push

tempo:
  enabled: true
  hostname: "observability.test.example.com"
  namespace: tempo
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system
  basicAuth:
    secretName: "tempo-basic-auth"
  read:
    paths:
    - /tempo/api/echo
    - /tempo/api/search
    grpc:
      backendService: tempo-query-frontend
      backendPort: 9095
  write:
    paths:
    - /v1/traces
    stripPrefixPaths: []
