name: observability-platform-api
serviceType: managed

loki:
  enabled: false
  namespace: loki
  # -- Hostname for all Loki routes. Supports Helm template strings.
  hostname: ""
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system

mimir:
  enabled: false
  namespace: mimir
  # -- Hostname for all Mimir routes. Supports Helm template strings.
  hostname: ""
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system

tempo:
  enabled: false
  namespace: tempo
  # -- Hostname for all Tempo routes. Supports Helm template strings.
  hostname: ""
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system

ingresses:
  - name: loki
    namespace: loki
    service:
      name: loki-gateway
      port: 80
    ingressClassName: nginx
    hosts:
      - host: observability.giantswarm.io
        paths: []
    # Optional: specify custom TLS secret name otherwise, the secret is shared in one namespace
    # tls:
    #   secretName: shared-observability-tls
  - name: mimir
    namespace: mimir
    service:
      name: mimir-gateway
      port: 80
    ingressClassName: nginx
    hosts:
      - host: observability.giantswarm.io
        paths: []
    # Optional: specify custom TLS secret name otherwise, the secret is shared in one namespace
    # tls:
    #   secretName: shared-observability-tls
